private ["_trad", "_ranx", "_rany", "_temppos", "_i", "_count", "_finpos", "_bob"];
{
	clearWeaponCargo _x;
	clearMagazineCargo _x;
	clearWeaponCargoGlobal _x;
	clearMagazineCargoGlobal _x;
	_x addBackpackCargoGlobal ["I44_Bag_M2MortarBP",1];
	_x addBackpackCargoGlobal ["I44_Bag_M2Mortar",1];
	_x addBackpackCargoGlobal ["I44_Bag_Vickers",1];
	_x addBackpackCargoGlobal ["I44_Bag_TripodV",1];
	_x addBackpackCargoGlobal ["I44_Bag_BABBergen",12];
	_x addBackpackCargoGlobal ["I44_Bag_BABNo4Mk1",6];
	_x addBackpackCargoGlobal ["I44_Bag_BABSten",3];
	_x addBackpackCargoGlobal ["I44_Bag_BABBren",3];
	_x addBackpackCargoGlobal ["I44_Bag_BABMedic",3];
	_x addBackpackCargoGlobal ["I44_Bag_BABPIAT",3];
	_x addBackpackCargoGlobal ["I44_Bag_BABRadio",3];
	_x addWeaponCargoGlobal ["I44_WebleyMk6",6];
	_x addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1",3];
	_x addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1_T",2];
	_x addWeaponCargoGlobal ["I44_StenMk2",3];
	_x addWeaponCargoGlobal ["I44_StenMk5",3];
	_x addWeaponCargoGlobal ["I44_BrenMk1",3];
	_x addWeaponCargoGlobal ["I44_PIAT",3];
	_x addWeaponCargoGlobal ["Binocular",2];
	_x addWeaponCargoGlobal ["I44_MedpackSmall",10];
	_x addWeaponCargoGlobal ["I44_MedpackLarge",10];
	_x addMagazineCargoGlobal ["I44_6rd_12x20R_Ball_WebleyMk6",48];
	_x addMagazineCargoGlobal ["I44_10rd_77x56R_Ball_LeeEnfield",100];
	_x addMagazineCargoGlobal ["I44_30rd_77x56R_Ball_Bren",36];
	_x addMagazineCargoGlobal ["I44_30rd_77x56R_Mix_Bren",48];
	_x addMagazineCargoGlobal ["I44_30rd_77x56R_Tracer_Bren",12];
	_x addMagazineCargoGlobal ["I44_32rd_9x19_Ball_Sten",60];
	_x addMagazineCargoGlobal ["I44_32rd_9x19_BallSS_Sten",60];
	_x addMagazineCargoGlobal ["I44_250rd_77x56R_Mix_Vickers_mounted",10];
	_x addMagazineCargoGlobal ["I44_Grenade_PIATMk3",12];
	_x addMagazineCargoGlobal ["I44_HandGrenade_No82",48];
	_x addMagazineCargoGlobal ["I44_HandGrenade_No36M",48];
	_x addMagazineCargoGlobal ["I44_SmokeGrenade_ANM8",48];
	_x addMagazineCargoGlobal ["I44_SmokeGrenade_M18Red",6];
	_x addMagazineCargoGlobal ["I44_SmokeGrenade_M18Green",6];
	_x addMagazineCargoGlobal ["I44_SmokeGrenade_M18Yellow",6];
	_x addMagazineCargoGlobal ["I44_SmokeGrenade_M18Violet",6];
	_x addMagazineCargoGlobal ["Pipebomb",6];
	_x addMagazineCargoGlobal ["Mine",3];
	_x addMagazineCargoGlobal ["I44_Mine_AT_GrenadeNo75",6];
	_x addMagazineCargoGlobal ["I44_12rd_60L12_M49A2",2];
	_x addMagazineCargoGlobal ["I44_12rd_60L12_M83A1",1];
	_x addMagazineCargoGlobal ["I44_12rd_60L12_M302",1];
	if (_x == Flight_1) then {
		Flight_1 flyinheight 150 + (random 50);
		_trad = 1200;
		_ranx = round ((random (2 * _trad)) - (1.5 * _trad));
		_rany = round ((random (2 * _trad)) - (1.3 * _trad));
		_count = (count (waypoints Ocelot) -1);
		for "_i" from (_count -4) to _count step 1 do {
			_temppos = waypointPosition [Ocelot, (_i)];
			[Ocelot, _i] setWaypointPosition [[((_temppos select 0) + _ranx), ((_temppos select 1) + _rany), (_temppos select 2)], 0];
			_finpos = waypointPosition [Ocelot, (_i)];
			_bob = format ["Original WP#%1 pos = %2 Now WP#%1 set to %3", _i, _temppos, _finpos];
			[_bob, "WPs", [false, true, false] ] call CBA_fnc_debug;
			//_temppos = getWPPos [Prawn, (_i)];
			//[Prawn, _i] setWPPos [((_temppos select 0) + _ranx), ((_temppos select 1) + _rany), (_temppos select 2)];
			//_temppos = getWPPos [Prawn, (_i)];
			//[KingPrawn, _i] setWPPos [((_temppos select 0) + _ranx), ((_temppos select 1) + _rany), (_temppos select 2)];
		};
		nul = [] execVM "dead\dfBoxInit.sqf";
	};
} forEach [Flight_1, Flight_2, Flight_3, Flight_4];
_trad = nil;
_ranx = nil;
_rany = nil;
_temppos = nil;