private [ "_box","_yco","_pos"];
_yco = 5027;
if (isServer) then {_mach = "server"} else {_mach = name player};
{
	_pos = [7124,_yco,0];
	_box = createVehicle ["I44_AmmoBox_airdropContainer",  _pos, [], 0, "NONE"];
	clearWeaponCargo _box;
	clearMagazineCargo _box;
	clearMagazineCargoGlobal _box;
	clearWeaponCargoGlobal _box;
	_box addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1",2];
	_box addWeaponCargoGlobal ["I44_StenMk5",2];
	_box addWeaponCargoGlobal ["I44_PIAT",2];
	_box addWeaponCargoGlobal ["I44_MedpackSmall",6];
	_box addWeaponCargoGlobal ["I44_MedpackLarge",6];
	_box addWeaponCargoGlobal ["I44_BrenMk1",3];
	_box addWeaponCargoGlobal ["I44_StenMk2",3];
	_box addBackpackCargoGlobal ["I44_Bag_M2Mortar",1];
	_box addMagazineCargoGlobal ["I44_32rd_9x19_Ball_Sten",60];
	_box addMagazineCargoGlobal ["I44_32rd_9x19_BallSS_Sten",60];
	_box addMagazineCargoGlobal ["I44_Grenade_PIATMk3",12];
	_box addMagazineCargoGlobal ["I44_30rd_77x56R_Mix_Bren",48];
	_box addMagazineCargoGlobal ["I44_30rd_77x56R_Tracer_Bren",12];
	_box addMagazineCargoGlobal ["I44_10rd_77x56R_Ball_LeeEnfield",75];
	_box addMagazineCargoGlobal ["I44_30rd_77x56R_Ball_Bren",36];
	_box addMagazineCargoGlobal ["I44_250rd_77x56R_Mix_Vickers_mounted",20];
	_box addMagazineCargoGlobal ["I44_6rd_12x20R_Ball_WebleyMk6",48];
	_box addMagazineCargoGlobal ["I44_Mine_AT_GrenadeNo75",6];
	_box addMagazineCargoGlobal ["I44_HandGrenade_No82",12];
	_box addMagazineCargoGlobal ["Pipebomb",6];
	_box addMagazineCargoGlobal ["Mine",3];
	_box addMagazineCargoGlobal ["I44_HandGrenade_No36M",48];
	_box addMagazineCargoGlobal ["I44_SmokeGrenade_ANM8",48];
	_box addMagazineCargoGlobal ["I44_SmokeGrenade_M18Red",6];
	_box addMagazineCargoGlobal ["I44_SmokeGrenade_M18Green",6];
	_box addMagazineCargoGlobal ["I44_SmokeGrenade_M18Yellow",6];
	_box addMagazineCargoGlobal ["I44_SmokeGrenade_M18Violet",6];
	missionNamespace setVariable [_x, _box];
	_yco = _yco + 2;
	sleep 0.5;
	} forEach ["f1c1", "f2c1", "f3c1", "f4c1"];
{
	_pos = [7126,_yco,0];
	_box = createVehicle ["I44_AmmoBox_airdropContainer",  _pos, [], 0, "NONE"];
	clearWeaponCargo _box;
	clearMagazineCargo _box;
	clearMagazineCargoGlobal _box;
	clearWeaponCargoGlobal _box;
	_box addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1",2];
	_box addWeaponCargoGlobal ["I44_StenMk5",2];
	_box addWeaponCargoGlobal ["I44_PIAT",1];
	_box addBackpackCargoGlobal ["I44_Bag_M2MortarBP",1];
	_box addWeaponCargoGlobal ["Binocular",2];
	_box addWeaponCargoGlobal ["I44_MedpackSmall",60];
	_box addWeaponCargoGlobal ["I44_MedpackLarge",60];
	_box addMagazineCargoGlobal ["I44_Grenade_PIATMk3",3];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M49A2",2];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M83A1",1];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M302",1];
	_box addMagazineCargoGlobal ["I44_10rd_77x56R_Ball_LeeEnfield",25];
	_box addMagazineCargoGlobal ["I44_30rd_77x56R_Mix_Bren",48];
	_box addMagazineCargoGlobal ["I44_Mine_AT_GrenadeNo75",6];
	missionNamespace setVariable [_x, _box];
	_yco = _yco + 2;
	sleep 0.5;
	} forEach ["f1c2", "f2c2", "f3c2", "f4c2"];
{
	_pos = [7128,_yco,0];
	_box = createVehicle ["I44_AmmoBox_airdropContainer",  _pos, [], 0, "NONE"];
	clearWeaponCargo _box;
	clearMagazineCargo _box;
	clearMagazineCargoGlobal _box;
	clearWeaponCargoGlobal _box;
	_box addBackpackCargoGlobal ["I44_Bag_M2Mortar",1];
	_box addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1",2];
	_box addWeaponCargoGlobal ["I44_StenMk5",2];
	_box addWeaponCargoGlobal ["I44_PIAT",1];
	_box addWeaponCargoGlobal ["I44_LeeEnfieldNo4Mk1_T",2];
	_box addWeaponCargoGlobal ["I44_BrenMk1",3];
	_box addWeaponCargoGlobal ["I44_StenMk2",3];
	_box addWeaponCargoGlobal ["Binocular",2];
	_box addWeaponCargoGlobal ["I44_MedpackSmall",10];
	_box addWeaponCargoGlobal ["I44_MedpackLarge",10];
	_box addMagazineCargoGlobal ["I44_Grenade_PIATMk3",3];
	_box addMagazineCargoGlobal ["Pipebomb",6];
	_box addMagazineCargoGlobal ["Mine",3];
	_box addMagazineCargoGlobal ["I44_Mine_AT_GrenadeNo75",6];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M49A2",2];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M83A1",1];
	_box addMagazineCargoGlobal ["I44_12rd_60L12_M302",1];
	_box addMagazineCargoGlobal ["I44_10rd_77x56R_Ball_LeeEnfield",100];
	_box addMagazineCargoGlobal ["I44_30rd_77x56R_Mix_Bren",30];
	_box addMagazineCargoGlobal ["I44_32rd_9x19_BallSS_Sten",30];
	missionNamespace setVariable [_x, _box];
	_yco = _yco + 2;
	sleep 0.5;
	} forEach ["f1c3", "f2c3", "f3c3", "f4c3"];