private ["_fp", "_targ", "_rand", "_loc", "_fuel"];
enableCamShake true;
enableEngineArtillery true;
Zernovo_Cap = "ned";
Stallone_Cap = "ned";
Pitt_Cap = "ned";
Osa_Cap = "ned";
Avdon_Cap = "ned";
FBArthur_Cap = "ned";
Factory_Cap = "ned";
FBBertie_Cap = "ned";
Lebedov_Cap = "ned";
RailDepot_Cap = "ned";
Panz_Cap = "ned";
_targ = ["vandal1", "vandal2", "vandal3", "vandal4", "vandal5"];
_rand = round random ((count _targ)-1);
_fp = _targ select _rand;
_loc  = getmarkerpos _fp;
_fuel = "I44_Plane_A_C47A_AAF" createVehicle _loc;
_fuel setposATL _loc;
_fuel setDammage 1;
{deletemarker _x; sleep 1} forEach _targ;
setWind [-4,4, false];
0 setOvercast 0.8;
0 setRain 0.8;
21600 setOvercast 0.4;
7200 setRain 0;